// <auto-generated />
using System;
using FisFaturaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FisFaturaAPI.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250620060506_CreateReceiptTable")]
    partial class CreateReceiptTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FisFaturaAPI.Models.Firm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EkleyenKullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("FirmaAdi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EkleyenKullaniciId");

                    b.ToTable("Firms");
                });

            modelBuilder.Entity("FisFaturaAPI.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaturaNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FaturaResimYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FaturaTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("FaturaTuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FirmaAliciId")
                        .HasColumnType("int");

                    b.Property<int?>("FirmaGonderenId")
                        .HasColumnType("int");

                    b.Property<string>("GelirGider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IcerikTuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KaydedenKullaniciId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("KdvToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Kdv_0")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Kdv_1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Kdv_10")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Kdv_18")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Kdv_20")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Kdv_8")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MatrahToplam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Matrah_0")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Matrah_1")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Matrah_10")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Matrah_18")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Matrah_20")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Matrah_8")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("OdemeTuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senaryo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tip")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FirmaAliciId");

                    b.HasIndex("FirmaGonderenId");

                    b.HasIndex("KaydedenKullaniciId");

                    b.HasIndex("UserId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("FisFaturaAPI.Models.Receipt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FirmaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FisNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FisResimYolu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GelirGider")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IcerikTuru")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("KdvOranlariJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("MatrahOranlariJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdemeSekli")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Tarih")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ToplamTutar")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VergiNo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Receipts");
                });

            modelBuilder.Entity("FisFaturaAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Isim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("datetime2");

                    b.Property<string>("ResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyisim")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TcKimlikNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("FisFaturaAPI.Models.Firm", b =>
                {
                    b.HasOne("FisFaturaAPI.Models.User", "EkleyenKullanici")
                        .WithMany("EkledigiFirmalar")
                        .HasForeignKey("EkleyenKullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EkleyenKullanici");
                });

            modelBuilder.Entity("FisFaturaAPI.Models.Invoice", b =>
                {
                    b.HasOne("FisFaturaAPI.Models.Firm", "FirmaAlici")
                        .WithMany("AliciOlduguFaturalar")
                        .HasForeignKey("FirmaAliciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FisFaturaAPI.Models.Firm", "FirmaGonderen")
                        .WithMany("GondericiOlduguFaturalar")
                        .HasForeignKey("FirmaGonderenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FisFaturaAPI.Models.User", "KaydedenKullanici")
                        .WithMany()
                        .HasForeignKey("KaydedenKullaniciId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("FisFaturaAPI.Models.User", null)
                        .WithMany("KaydettigiFaturalar")
                        .HasForeignKey("UserId");

                    b.Navigation("FirmaAlici");

                    b.Navigation("FirmaGonderen");

                    b.Navigation("KaydedenKullanici");
                });

            modelBuilder.Entity("FisFaturaAPI.Models.Firm", b =>
                {
                    b.Navigation("AliciOlduguFaturalar");

                    b.Navigation("GondericiOlduguFaturalar");
                });

            modelBuilder.Entity("FisFaturaAPI.Models.User", b =>
                {
                    b.Navigation("EkledigiFirmalar");

                    b.Navigation("KaydettigiFaturalar");
                });
#pragma warning restore 612, 618
        }
    }
}
